---
title: "NOAA_dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r include=FALSE}
library(dplyr)
library(tidyverse)
library(readxl)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

```{r}
#read and clean the data
nynoaadat <- read_csv("./data/nynoaadat.zip") %>%
  clean_names() %>% 
  separate(.,date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(month = as.numeric(month))
```


Column {data-width=400}
-----------------------------------------------------------------------

### Boxplot of snowfall distribution of each month

```{r}
#make a boxplot of the distribution of snowfall for each month, sequencing from the lowest median snowfall to the highest median snowfall.
nynoaadat_box <- nynoaadat %>% 
  filter(snow > 0 & snow < 100) %>% 
  group_by(month) %>% 
  mutate(med_snow = median(snow, na.rm = TRUE)) %>% 
  ungroup(month) %>% 
  mutate(month_str = month.abb[month],
         month_str = fct_reorder(month_str, med_snow)) %>% 
  rename(snowfall = snow)
nynoaadat_box_plotly = plot_ly(nynoaadat_box, y = ~snowfall, color = ~month_str, type = "box") %>% 
    layout(yaxis = list(title = "Snowfall"))
nynoaadat_box_plotly
```

Column {data-width=350}
-----------------------------------------------------------------------

### Scatterplot of average max temperature against average min temperature

```{r}
#make a scatter plot of mean of maximum temperature against minimum temperature for each month
nynoaadat_scatter <- nynoaadat%>% 
  filter(is.na(tmax) == FALSE, is.na(tmin) == FALSE) %>% 
  mutate(tmax1 = as.numeric(tmax)/10, tmin1 = as.numeric(tmin)/10) %>% 
  group_by(year, month) %>% 
  summarise(maximum_temperature = mean(tmax1, na.rm = TRUE),
            minimum_temperature = mean(tmin1, na.rm = TRUE)) %>% 
  mutate(month_str = month.name[month],
         text_label = str_c("Year: ",year,'; Month: ', month_str))
nynoaadat_scatter_plotly = plot_ly(nynoaadat_scatter, x = ~minimum_temperature, y =  ~maximum_temperature, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~month_str,
          text = ~text_label) %>% 
       layout(xaxis = list(title = "Minimum temperature"),
         yaxis = list(title = "Maximum temperature"))
nynoaadat_scatter_plotly
```

### Barplot of average snowfall

```{r}
#make a barplot of the average snowfall of each year
nynoaadat_bar <- nynoaadat %>% 
   filter(snow > 0 & snow < 100) %>% 
   group_by(year) %>% 
   summarize(average_snallfall = round(mean(snow, na.rm = TRUE),3)) %>% 
   mutate(text_label = str_c("Year: ",year,'; Average Snowfall: ',average_snallfall))
nynoaadat_bar_plotly = plot_ly(nynoaadat_bar, x = ~year, y = ~average_snallfall, type = "bar",
           color = ~year,
           text = ~text_label) %>% 
  layout(xaxis = list(title = "year"),
    yaxis = list(title = "Average snowfall"))
nynoaadat_bar_plotly
```

