---
title: "plotly"
author: "Shumin Rui"
date: "11/9/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(rnoaa)
library(tidyverse)
library(readxl)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
```

```{r}
#read and clean the data
nynoaadat <- read_csv("./data/nynoaadat.csv.zip") %>%
  clean_names() %>% 
  separate(.,date, into = c("year", "month", "day"), sep = "-")
```

```{r}
#make a scatter plot of mean of maximum temperature against minimum temperature for each month.
nynoaadat_scatter <- nynoaadat%>% 
  filter(is.na(tmax) == FALSE, is.na(tmin) == FALSE) %>% 
  mutate(tmax1 = as.numeric(tmax)/10, tmin1 = as.numeric(tmin)/10) %>% 
  group_by(year, month) %>% 
  summarise(mean_tmax = mean(tmax1, na.rm = TRUE),
            mean_tmin = mean(tmin1, na.rm = TRUE)) %>% 
  mutate(month_str = month.name[as.numeric(month)],
         text_label = str_c("Year: ",year,'; Month: ', month_str)) %>%
  plot_ly(x = ~mean_tmin, y =  ~mean_tmax, type = "scatter", mode = "markers",
          alpha = 0.5, 
          color = ~month,
          text = ~text_label)
nynoaadat_scatter
```

```{r}
#make a boxplot of the distribution of snowfall for each month, sequencing from the lowest median snowfall to the highest median snowfall.
nynoaadat_box <- nynoaadat %>% 
  filter(snow > 0 & snow < 100) %>% 
  group_by(month) %>% 
  mutate(med_snow = median(snow, na.rm = TRUE)) %>% 
  ungroup(month) %>% 
  mutate(month_str = month.name[as.numeric(month)],
         month_str = fct_reorder(month_str, med_snow)) %>% 
  plot_ly(y = ~snow, color = ~month_str, type = "box",
          colors = "Set2")
nynoaadat_box
```

```{r}
#make a barplot of the average snowfall of each year
nynoaadat_bar <- nynoaadat %>% 
   filter(snow > 0 & snow < 100) %>% 
   group_by(year) %>% 
   summarize(snow_ave = round(mean(snow, na.rm = TRUE),3)) %>% 
   mutate(text_label = str_c("Year: ",year,'; Average Snowfall: ',snow_ave)) %>% 
   plot_ly(x = ~year, y = ~snow_ave, type = "bar",
           color = ~year,
           text = ~text_label)
nynoaadat_bar
```




